"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv  # type: ignore
import os
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.templatetags.static import static

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()  # take environment variables from .env file

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG")

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", "http://localhost:8000").split(",")

# Application definition

INSTALLED_APPS = [
    
    "unfold",
    "accounts",
    "unfold.contrib.filters",  # Optional but recommended
    "unfold.contrib.forms",  # Optional
    "unfold.contrib.inlines",
    "django_filters",  # For advanced filtering in admin and API
    "django_htmx",  # For HTMX support in Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",  # ← Enables |naturalday, |intcomma, etc
    # rest framework and JWT
    "rest_framework",
    "rest_framework_simplejwt",
    # cors headers
    "corsheaders",
    # Local apps
    
    'shop_manager.apps.ShopManagerConfig',
    "widget_tweaks",
]

INSTALLED_APPS += [
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware", # HTMX middleware for handling HTMX requests
]

ROOT_URLCONF = "backend.urls"

# CORS_ALLOWED_ORIGINS
CORS_ALLOWED_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS", "").split(",")

# MUST be True when using withCredentials / cookies
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_ALL_ORIGINS = os.getenv("CORS_ALLOW_ALL_ORIGINS", "False").lower() == "true"

# Recommended for cross-origin session cookies in dev
# SESSION_COOKIE_SAMESITE = 'None'      # or 'Lax'
# CSRF_COOKIE_SAMESITE = 'None'
# SESSION_COOKIE_SECURE = False         # dev only (http)
# CSRF_COOKIE_SECURE = False

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",  # ← must include this
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Nairobi"

USE_I18N = True

USE_TZ = True

# email settings for sending verification and password reset emails
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = os.getenv("EMAIL_PORT", 587)
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")


# Celery Configuration
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Africa/Nairobi"
CELERY_ENABLE_UTC = False

# Optional: task retry settings for email (in case SMTP temporarily fails)
CELERY_TASK_DEFAULT_RETRY_DELAY = 60  # seconds
CELERY_TASK_MAX_RETRIES = 5


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Where Django looks for static files during collectstatic
STATICFILES_DIRS = [
    BASE_DIR / "static",  # your custom static files
]

# Where collectstatic puts files in production
STATIC_ROOT = "/var/www/kanainvestments-static/"


FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:5173")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


AUTH_USER_MODEL = "accounts.User"


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
}


AUTHENTICATION_BACKENDS = [
    "accounts.backends.CaseInsensitiveEmailBackend",  # custom backend for case-insensitive email login
    "allauth.account.auth_backends.AuthenticationBackend",
    "django.contrib.auth.backends.ModelBackend",  # ← keep this if you want to allow username login for admin or legacy reasons
]

# =============================================================================
# AUTH & ALLAUTH - Fixed Redirect Loop + Admin Integration
# =============================================================================
SITE_ID = 1

ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "optional"

ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = True

# Force admin to use allauth login
LOGIN_URL = "admin:login"                    # Use Django's default admin login
LOGIN_REDIRECT_URL = "admin:index"
ACCOUNT_LOGOUT_REDIRECT_URL = "admin:login"


# Important: Make sure allauth handles staff login properly
ACCOUNT_AUTHENTICATION_METHOD = "email"   # Keep for compatibility


# Google provider – secure env config (no DB SocialApp needed)
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
        "APP": {
            "client_id": os.getenv("GOOGLE_CLIENT_ID"),
            "secret": os.getenv("GOOGLE_CLIENT_SECRET"),
            "key": "",
        },
    }
}

# Use custom signup form to remove username field
ACCOUNT_FORMS = {
    "signup": "accounts.forms.CustomSignupForm",
}

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),  # short lived access token
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),  # longer refresh token
    "ROTATE_REFRESH_TOKENS": True,  # issue new refresh on refresh
    "BLACKLIST_AFTER_ROTATION": True,  # blacklist old refresh token
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}


# =============================================================================
# UNFOLD DASHBOARD (Updated to match current models)
# =============================================================================
UNFOLD = {
    "SITE_TITLE": "Inventory Manager",
    "SITE_HEADER": "Manager Dashboard",
    "SITE_URL": "/",
    "SITE_SYMBOL": "school",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "DASHBOARD_CALLBACK": "backend.utils.dashboard.dashboard_callback",  # keep if you have it
    "COLORS": {
        "primary": {
             "50": "#f0f9ff",

            "100": "#e0f2fe",

            "200": "#bae6fd",

            "300": "#7dd3fc",

            "400": "#38bdf8",

            "500": "#0ea5e9",

            "600": "#0284c7",

            "700": "#0369a1",

            "800": "#075985",

            "900": "#0c3d66",
        },
    },

    # Dark mode settings
    "DARK_MODE_THEME": "django-admin-darkly",

    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("Core"),
                "icon": "storefront",
                "items": [
                    {
                        "title": _("My Shop"),           # ← NOW POINTS TO DASHBOARD
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                    # {
                    #     "title": _("Manage Shop Details"),
                    #     "icon": "store",
                    #     "link": reverse_lazy("admin:shop_manager_shop_changelist"),
                    # },
                    {
                        "title": _("Users"),
                        "icon": "people",
                        "link": reverse_lazy("admin:accounts_user_changelist"),
                        "permission": lambda r: r.user.role in ["SuperAdmin", "ShopAdmin"],
                    },
                ],
            },
            {
                "title": _("Product Catalog"),
                "icon": "category",
                "items": [
                    {
                        "title": _("Categories"),
                        "icon": "category",
                        "link": reverse_lazy("admin:shop_manager_category_changelist"),
                    },
                    {
                        "title": _("Suppliers"),
                        "icon": "local_shipping",
                        "link": reverse_lazy("admin:shop_manager_supplier_changelist"),
                    },
                    {
                        "title": _("Products"),
                        "icon": "precision_manufacturing",
                        "link": reverse_lazy("admin:shop_manager_product_changelist"),
                    },
                    {
                        "title": _("Current Stock"),
                        "icon": "warehouse",
                        "link": reverse_lazy("admin:shop_manager_stock_changelist"),
                    },
                ],
            },
            {
                "title": _("Daily Students Present"),
                "icon": "group",
                "items": [
                    {
                        "title": _("Record Today"),           # ← Quick one-click entry
                        "icon": "add",
                        "link": "/api/shopmanager/record-today/",
                    },
                    {
                        "title": _("View All Records"),
                        "icon": "list",
                        "link": reverse_lazy("admin:shop_manager_dailystudentrecord_changelist"),
                    },
                ],
            },
            {
                "title": _("Transactions"),
                "icon": "swap_horiz",
                "items": [
                    {
                        "title": _("Purchases"),
                        "icon": "shopping_cart",
                        "link": reverse_lazy("admin:shop_manager_purchase_changelist"),
                    },
                    {
                        "title": _("New Purchase"),
                        "icon": "add_shopping_cart",
                        "link": "/api/shopmanager/add-purchase/",  # from custom view
                    },
                    {
                        "title": _("Usage / Consumption"),
                        "icon": "point_of_sale",
                        "link": reverse_lazy("admin:shop_manager_usage_changelist"),
                    },
                    {
                        "title": _("New Usage"),
                        "icon": "add",
                        "link": "/api/shopmanager/add-usage/",  # from custom view
                    },
                    {
                        "title": _("Expenses"),
                        "icon": "receipt_long",
                        "link": reverse_lazy("admin:shop_manager_expense_changelist"),
                    },
                    
                ],
            },
            {
                "title": _("Reports & Analytics"),
                "icon": "analytics",
                "items": [
                    {
                        "title": _("Usage Report"),
                        "icon": "trending_up",
                        "link": "/reports/usage/",
                    },
                    {
                        "title": _("Purchase Report"),
                        "icon": "shopping_cart",
                        "link": "/reports/purchases/",
                    },
                    # {
                    #     "title": _("Expense Report"),
                    #     "icon": "receipt_long",
                    #     "link": "/reports/expenses/",
                    # },
                    {
                        "title": _("Stock Report"),
                        "icon": "inventory_2",
                        "link": "/reports/stock/",
                    },
                ],
            },
        ],
    },
}
